name: app_iot_sistema_riego
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_database: ^11.2.1
  table_calendar: ^3.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

# Configuración del icono de la aplicación
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  # Personaliza los colores para un icono adaptativo en Android
  adaptive_icon_background: "#2196F3"  # Azul agua
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
